-- Add ML integration fields to persons table
-- These fields support the face enrollment and ML service integration

-- Add field to track when face embeddings were last generated
ALTER TABLE persons ADD COLUMN face_embeddings_generated_at TIMESTAMP;

-- Add field to track the number of face images used for embeddings
ALTER TABLE persons ADD COLUMN face_image_count INTEGER DEFAULT 0;

-- Add field to track ML service processing status
ALTER TABLE persons ADD COLUMN face_processing_status VARCHAR(50) DEFAULT 'PENDING';

-- Add field to store any ML processing errors
ALTER TABLE persons ADD COLUMN face_processing_error TEXT;

-- Create index for face processing queries
CREATE INDEX idx_persons_face_processing_status ON persons(face_processing_status);
CREATE INDEX idx_persons_face_embeddings_generated_at ON persons(face_embeddings_generated_at);

-- Add comment to face_vector field to document its purpose
COMMENT ON COLUMN persons.face_vector IS 'JSON array of face embeddings generated by ML service for facial recognition';
COMMENT ON COLUMN persons.face_embeddings_generated_at IS 'Timestamp when face embeddings were last generated';
COMMENT ON COLUMN persons.face_image_count IS 'Number of images used to generate face embeddings';
COMMENT ON COLUMN persons.face_processing_status IS 'Status of face processing: PENDING, PROCESSING, COMPLETED, FAILED';
COMMENT ON COLUMN persons.face_processing_error IS 'Error message if face processing failed';
